### PR TITLE
Fix small tasks keyspace limit

### PR DESCRIPTION
**Pull request by imjustanoob**
Smalls tasks were given a limit of 1 instead of the entire keyspace.

### CODE REVIEW

**Comment by s3inlc** [comment]
Can you please explain more detailed what this pull request should fix?

And why did you revert the latest commits on the master?

**Comment by imjustanoob** [comment]
Small tasks were being broken into chunks with limit 1, because of the conditional error. 

The second commit, is me not knowing how to github.. not sure if you can ignore it or I have to do a repull.

**Comment by s3inlc** [comment]
Ok thanks, I guess I see what the idea of the fix is.
If it's ok for you I'll just apply the change to master and then close this pull request, I think this is easier than try to revert the faulty merge here.

**Comment by imjustanoob** [comment]
That works.

**Comment by s3inlc** [comment]
Thanks for the contribution. Fix is pushed to master.

**Pull request closed without merging**
