### PR TITLE
Mask API keys for other users with config setting

### PR DESCRIPTION
**Pull request by noncenz**
Addressing enhancement #565 this change masks viewing of other user's API keys by administrators. This change also prevents reassignment of API keys between users. 

Set `$MASK_API_KEYS = true` in conf.php to activate the feature.

### CODE REVIEW

**Comment by s3inlc** [comment]
Hey, sorry about the delay. Thanks for opening the PR providing this feature, some points to consider:
- The conf.php is not thought to put such config values in there, it's only for the installation setup (MySQL settings). If possible please use the same way as all other config variables are set (defined in src/inc/defines/config.php and created in the sql setup and the upgrade scripts)
- What is the way how admins give the api keys to their according users after creation if they cannot see it? (Note that normally users don't have full admin rights and therefore cannot see this section to get their own API key)
- The key owner change check should be executed directly in the action handler switch case and not outside of it.

**Comment by noncenz** [comment]
Hi Sien, I think I'll need a little more guidance on this - I read the enhancement as the app instance having multiple admins and we don't want admins to see each other's API keys. 

- We can't expose the config setting to Admins through the GUI as they could just turn it off. Would it the best to add it to the database and just not map to the UI, or maybe use an include file other than conf.php?

- I had assumed all users were admins in this case and they would see their own keys through the API Management screen; an oversight on my part. Regular users will need to see keys without exposing them to an admin. Should we list them out under My Account > Settings? Or perhaps admins can see all user keys but other admin keys are masked?

**Comment by s3inlc** [comment]
- You're right, didn't thought at that the admins could easily change the config. I will have to think about what the ideal solution would be to put that config. Maybe the conf.php would be good, but I would like to avoid global variables, maybe some other construct.
- Yeah, showing a users' own keys would be the best solution I think (at the location you proposed). This would also work for admins then, so all api keys on the config could be masked and admins also can see their own keys on their account page.

**Comment by s3inlc** [comment]
Sorry about the big delay, I didn't had time so far to have a look at it. The code looks great, I'll merge it now and then maybe change some minor details later.
Thanks for the contribution!

**Pull request merged**
